version: 2
build:
  os: ubuntu-24.04
  tools:
    python: "3.14"
    nodejs: latest
  jobs:
    create_environment:
      - asdf plugin add uv
      - asdf install uv latest
      - asdf global uv latest
    build:
      html:
        - uvx hatch run docs:build -W # do not remove -W, fix warnings.
        - mv docs/_build $READTHEDOCS_OUTPUT
