version: 2
build:
  os: ubuntu-24.04
  tools:
    python: "3.13"
  jobs:
    create_environment:
      - asdf plugin add uv
      - asdf install uv latest
      - asdf global uv latest
      - run: |
          uvx hatch run hatch-test.py3.13:python - <<'PYCODE'
          import importlib.metadata as m
          for dist in sorted(m.distributions(), key=lambda d: d.metadata["Name"].lower()):
              print(f"{dist.metadata['Name']}=={dist.version}")
          PYCODE
    build:
      html:
        - uvx hatch run docs:build
        - mv docs/_build $READTHEDOCS_OUTPUT
