version: 2
build:
  os: ubuntu-24.04
  tools:
    python: "3.13"
  jobs:
    post_install:
      - pip install uv
      - VIRTUAL_ENV=$READTHEDOCS_VIRTUALENV_PATH uv pip install .[doc]
sphinx:
  configuration: docs/conf.py
  fail_on_warning: true
